apiVersion: v1
kind: Service
metadata:
  name: apiserver
spec:
  type: NodePort
  ports:
  - name: http
    port: 9000
    nodePort: 30005
  selector:
    app: apiserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app: apiserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver
        image: andyj29/api:latest
        ports:
        - name: http
          containerPort: 9000