apiVersion: v1
kind: Service
metadata:
  name: nanobox
spec:
  ports:
  - name: grpc
    port: 8000
  - name: raft
    port: 4000
  clusterIP: None
  selector:
    app: nanobox

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nanobox
spec:
  serviceName: "nanobox"
  replicas: 4
  selector:
    matchLabels:
      app: nanobox
  template:
    metadata:
      labels:
        app: nanobox
    spec:
      containers:
      - name: nanobox
        image: andyj29/nanobox:latest
        ports:
        - name: grpc
          containerPort: 8000
        - name: raft
          containerPort: 4000
        volumeMounts:
        - name: raftdir
          mountPath: ./raftdir
        env:
        - name: ORDINAL_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_NAME
          value: "nanobox"
  volumeClaimTemplates:
  - metadata:
      name: raftdir
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: fast-disks
      resources:
        requests:
          storage: 20Gi

