apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nanobox
spec:
  serviceName: "nanobox"
  replicas: 4
  selector:
    matchLabels:
      app: nanobox
  template:
    metadata:
      labels:
        app: nanobox
    spec:
      containers:
      - name: nanobox
        image: 

