apiVersion: v1
kind: Service
metadata:
  name: apiserver
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9000
  selector:
    app: apiserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app: apiserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver
        image: andyj29/api:amd64
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9000